### ISSUE TITLE
Definição de áreas funcionais

### ISSUE THREAD

**Issue by cyz** [WoMakersCode/onboarding-voluntarios#1]
Quais são as áreas necessárias para gestão e expansão da comunidade?

**Comment by cyz** [comment]
IMHO: Comunicação, Treinamentos, Relacionamento e Mobilização.

**Comment by cyz** [comment]
**Possíveis atribuições de cada área: **

**Comunicação**: publicação no blog, divulgação de eventos nossos e de parceiros, postagem em redes sociais, networking com apoiadores, desenho de materiais gráficos e moderação de conteúdo do grupo de facebook.

**Treinamentos**: ministração de conteúdos presenciais, online e ajuda com exercícios (criação e possíveis correções). Pode-se considerar: palestras, mini cursos presenciais ou online, criação de exercícios, correção de exercícios, monitoria de mini cursos e plantão tira dúvidas em lives. 

**Relacionamento**: networking com parceiros de ações e apoio a comunicação.

**Mobilização**: líderes locais e de engajamento, para ajudar a amplificar e organizar as atividades e campanhas da comunidade.

**Comment by barrosgeraldo** [comment]
Estou trabalhando nesta: https://paper.dropbox.com/doc/Mobilizao-2017-WoMakesCode-hkdxm0OjuA2A5wi0NQO4m

**Comment by cyz** [comment]
Preenchi as áreas que estavam faltando na pastinha dos papers :)
